events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    limit_req_zone $binary_remote_addr zone=prodstack_limit:10m rate=10r/s;

    upstream prodstack_backend {
        server app-app-1:5000 max_fails=3 fail_timeout=30s;
        server app-app-2:5000 max_fails=3 fail_timeout=30s;
        server app-app-3:5000 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 80;
        server_name prodstack.local;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name prodstack.local;

        ssl_certificate     /etc/nginx/ssl/prodstack.crt;
        ssl_certificate_key /etc/nginx/ssl/prodstack.key;

        location /health {
            access_log off;
            return 200 'nginx ok\n';
            add_header Content-Type text/plain;
        }

        location / {
            limit_req zone=prodstack_limit burst=20 nodelay;
            limit_req_status 429;

            proxy_pass http://prodstack_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
            proxy_next_upstream error timeout http_500 http_502 http_503;
        }
    }
}
